spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hair?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wlxy.hair.model
app:
  imgPath: root/imag/
  info: this is wap
  author: zhai
  email: 111111111@qq.com
  swaggerTitle: 这是我们的swagger在线测试文档
  swaggerContactName: 翟晓猛
  swaggerContactWebUrl: https://www.baidu.com
  swaggerContactEmail: 982601770@qq.com
  swaggerVersion: v1.0.0
  swaggerDescription: springboot 在线接口文档
  swaggerTermsOfServiceUrl: https://www.baidu.com


logging:
  level:
    com.wlxy.hair.dao : debug


pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
server:
  tomcat:
    uri-encoding: UTF-8
